# Generated by Django 4.2.4 on 2023-08-30 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id_address', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ward_name', models.CharField(max_length=200)),
                ('district_name', models.CharField(max_length=200)),
                ('square', models.CharField(max_length=50)),
                ('population', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('note', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_docID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=250)),
                ('abstract_source', models.TextField()),
                ('history', models.TextField()),
                ('image', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='StreetGroup',
            fields=[
                ('group_streetID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=250)),
                ('number_member', models.IntegerField()),
                ('description', models.TextField()),
                ('note', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='StreetType',
            fields=[
                ('type_streetID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=250)),
                ('abstract_type', models.TextField()),
                ('document_regulation', models.CharField(max_length=300)),
                ('note', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('usertype', models.CharField(max_length=200)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(max_length=200)),
                ('style_id', models.IntegerField()),
                ('verified', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('street_name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('abstract', models.TextField()),
                ('content', models.CharField(max_length=450)),
                ('position', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('lane_number', models.IntegerField()),
                ('google_map', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=400)),
                ('group_streetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenDuong.streetgroup')),
                ('id_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenDuong.address')),
                ('source_docID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenDuong.source')),
                ('type_streetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenDuong.streettype')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenDuong.user')),
            ],
        ),
    ]
