# Generated by Django 4.2.4 on 2024-03-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenDuong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='street',
            name='length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='street',
            name='width',
            field=models.FloatField(),
        ),
    ]
