# Generated by Django 4.2.4 on 2024-03-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenDuong', '0002_street_image1_alter_street_length_alter_street_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='street_mapid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
